#!/bin/bash

# Get action
action=$1
shift

# Get command
cmd=$@

function usage() {
    echo "  Repeat a todo command whenever the todo.txt changes"
    echo "    $(basename $0) [COMMAND]"
    echo ""
    echo "      Usage"
    echo "        \$ todo.sh $(basename $0) [COMMAND]"
    echo ""
    echo "      Examples"
    echo "        \$ todo.sh $(basename $0) ls +project"
    echo "        \$ todo.sh $(basename $0) lsp @contect"
    echo ""
    exit
}

function watch() {
    ls $TODO_DIR/* | entr -c -c sh -c "echo \"watch ${cmd}\" && echo \"--\" && $TODO_FULL_SH $cmd"
    exit
}

[ "$action" = "usage" ] && usage
[ "$action" = "watch" ] && watch
